formatting:
  ImportOrdering:
    layout: '*'

style:
  ForbiddenComment:
    allowedPatterns: 'TODO:'
  MaxLineLength:
    maxLineLength: 200

complexity:
  LongMethod:
    active: false
  LongParameterList:
    functionThreshold : 15