style:
  ForbiddenComment:
    allowedPatterns: 'TODO:'
  MaxLineLength:
    maxLineLength: 200
  UseCheckOrError:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    functionThreshold : 15