=begin
#Hypto IAM

#APIs for Hypto IAM Service.

The version of the OpenAPI document: 1.0.0
Contact: engineering@hypto.in
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IamRuby::CreateOrganizationResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IamRuby::CreateOrganizationResponse do
  let(:instance) { IamRuby::CreateOrganizationResponse.new }

  describe 'test an instance of CreateOrganizationResponse' do
    it 'should create an instance of CreateOrganizationResponse' do
      expect(instance).to be_instance_of(IamRuby::CreateOrganizationResponse)
    end
  end
  describe 'test attribute "organization"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "admin_user_credential"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
