/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.hypto.iam.models


/**
 * 
 * @param id 
 * @param resourceId 
 * @param name 
 * @param description 
 */
data class Action(
    val id: java.util.UUID? = null,
    val resourceId: java.util.UUID? = null,
    val name: kotlin.String? = null,
    val description: kotlin.String? = null
) 

