/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.hypto.iam.models


/**
 * 
 * @param id 
 * @param validUntil 
 * @param status 
 * @param secret 
 */
data class Credential(
    val id: java.util.UUID? = null,
    val validUntil: kotlin.String? = null,
    val status: Credential.Status? = null,
    val secret: kotlin.String? = null
) 
{
    /**
    * 
    * Values: active,inactive
    */
    enum class Status(val value: kotlin.String){
        active("active"),
        inactive("inactive");
    }
}

