/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.hypto.iam.models


/**
 * 
 * @param code error code
 * @param message error description
 */
data class ErrorResponse(
    /* error code */
    val code: kotlin.String,
    /* error description */
    val message: kotlin.String
) 

