/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.hypto.iam.models


/**
 * 
 * @param success 
 * @param &#x60;data&#x60; 
 */
data class Model401Response(
    val success: kotlin.Boolean? = null,
    val `data`: kotlin.String? = null
) 

