=begin
#Hypto IAM

#APIs for Hypto IAM Service.

The version of the OpenAPI document: 1.0.0
Contact: engineering@hypto.in
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

# Common files
require 'iam-ruby/api_client'
require 'iam-ruby/api_error'
require 'iam-ruby/version'
require 'iam-ruby/configuration'

# Models
require 'iam-ruby/models/action'
require 'iam-ruby/models/action_paginated_response'
require 'iam-ruby/models/admin_user'
require 'iam-ruby/models/base_success_response'
require 'iam-ruby/models/create_action_request'
require 'iam-ruby/models/create_credential_request'
require 'iam-ruby/models/create_organization_request'
require 'iam-ruby/models/create_organization_response'
require 'iam-ruby/models/create_policy_request'
require 'iam-ruby/models/create_resource_request'
require 'iam-ruby/models/create_user_request'
require 'iam-ruby/models/credential'
require 'iam-ruby/models/credential_without_secret'
require 'iam-ruby/models/error_response'
require 'iam-ruby/models/get_user_policies_response'
require 'iam-ruby/models/organization'
require 'iam-ruby/models/pagination_options'
require 'iam-ruby/models/policy'
require 'iam-ruby/models/policy_association_request'
require 'iam-ruby/models/policy_paginated_response'
require 'iam-ruby/models/policy_statement'
require 'iam-ruby/models/resource'
require 'iam-ruby/models/resource_action'
require 'iam-ruby/models/resource_action_effect'
require 'iam-ruby/models/resource_paginated_response'
require 'iam-ruby/models/token_response'
require 'iam-ruby/models/update_action_request'
require 'iam-ruby/models/update_credential_request'
require 'iam-ruby/models/update_organization_request'
require 'iam-ruby/models/update_policy_request'
require 'iam-ruby/models/update_resource_request'
require 'iam-ruby/models/update_user_request'
require 'iam-ruby/models/user'
require 'iam-ruby/models/user_paginated_response'
require 'iam-ruby/models/user_policy'
require 'iam-ruby/models/validation_request'
require 'iam-ruby/models/validation_response'

# APIs
require 'iam-ruby/api/organization_management_api'
require 'iam-ruby/api/policy_management_api'
require 'iam-ruby/api/resource_action_management_api'
require 'iam-ruby/api/resource_management_api'
require 'iam-ruby/api/user_authorization_api'
require 'iam-ruby/api/user_credential_management_api'
require 'iam-ruby/api/user_management_api'
require 'iam-ruby/api/user_policy_management_api'

module IamRuby
  class << self
    # Customize default settings for the SDK using block.
    #   IamRuby.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
