/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.hypto.iam.server.models

import java.io.Serializable
/**
 * Administrator user details for the organization
 * @param passwordHash
 * @param email
 * @param phone
 * @param username
 */
data class AdminUser(
    val passwordHash: kotlin.String,
    val email: kotlin.String,
    val phone: kotlin.String,
    val username: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }
}
