/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.hypto.iam.server.models

import java.io.Serializable
/**
 * Payload to create ledger account
 * @param username
 * @param passwordHash
 * @param email
 * @param status
 * @param phone
 */
data class CreateUserRequest(
    val username: kotlin.String,
    val passwordHash: kotlin.String,
    val email: kotlin.String,
    val status: CreateUserRequest.Status,
    val phone: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }
    /**
    *
    * Values: active,inactive
    */
    enum class Status(val value: kotlin.String) {
        active("active"),
        inactive("inactive");
    }
}
