/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.hypto.iam.server.models

import java.io.Serializable
/**
 * Payload to attach / detach a policy to a user / resource
 * @param policies
 */
data class PolicyAssociationRequest(
    val policies: kotlin.collections.List<kotlin.String>
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }
}
