/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* OpenAPI spec version: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package com.hypto.iam.server.models

/**
 *  * @param id  * @param name  * @param version  * @param statements */
data class Policy(
    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val version: kotlin.String? = null,
    val statements: kotlin.Array<PolicyStatement>? = null
)
