/**
* Hypto IAM
* APIs for Hypto IAM Service.
*
* The version of the OpenAPI document: 1.0.0
* Contact: engineering@hypto.in
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.hypto.iam.server.models

import java.io.Serializable
/**
 * Payload to create ledger account
 * @param email
 * @param phone
 * @param status
 */
data class UpdateUserRequest(
    val email: String? = null,
    val phone: String? = null,
    val status: Status? = null,
    val verified: Boolean? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }
    /**
    *
    * Values: enabled,disabled
    */
    enum class Status(val value: String) {
        enabled("enabled"),
        disabled("disabled");
    }
}
