name: Build Project

on:
  pull_request:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Run Postgres
        run: |
          docker-compose -f docker-compose.yml up -d pg
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '6.9.2'
          arguments: build
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/jacoco/test/jacocoTestReport.csv
